#Eureak的配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1010/eureka/ #注册中心的注册地址
  instance:
    instance-id: user:1052 #服务的实例ID(右边的)
    prefer-ip-address: true #使用IP注册到Eureak
    lease-renewal-interval-in-seconds: 5 # 客户端续约频率
server:
  port: 1052
spring:
  application:
    name: service-user #服务的名字
# info配置
info:
# 项目的名称
  app.name: 源码项目
# 公司的名称
  company.namee: MiaoDaWei之家