#Eureak的配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1010/eureka/ #注册中心的注册地址
    registry-fetch-interval-seconds: 5 # 修改客户端拉取注册中心注册表的时间
  instance:
    instance-id: order:1020 #服务的实例ID(右边的)
    prefer-ip-address: true #使用IP注册到Eureaka
    lease-renewal-interval-in-seconds: 5 # 客户端续约频率
server:
  port: 1020
spring:
  application:
    name: service-order #服务的名字
ribbon:
  ReadTimeout: 2000                #读取超时时间
  ConnectTimeout: 2000          #链接超时时间
  MaxAutoRetries: 1             #重试机制：同一台实例最大重试次数
  MaxAutoRetriesNextServer: 1     #重试负载均衡其他的实例最大重试次数
  OkToRetryOnAllOperations: false #是否所有操作都重试，因为针对post请求如果没做幂等处理可能会造成数据多次添加/修改
  eager-load:
    enabled: true #开启饥饿加载
    clients: service-user #针对于哪些服务需要饥饿加载

